/**
 * index-writer：INDEX.md 决策段落引擎化（ADR-014 投影所有权）。
 * 「决策记录」「城市评估」段落由 decisions/ 真相源派生（person 列 = person_id → display_name 继承），
 * 带 generated 标记——Agent 不得手动修改该段；用户画像/公司尽调等段落保留 Agent 维护。
 */
import { parseSummaryTable } from '../ir/summary-table.ts'
import type { DecisionRecord } from '../ir/schema.ts'
import { scanPersons } from './person-watcher.ts'
import type { ParsedDecision } from './report-watcher.ts'
import type { Workspace } from './workspace.ts'

const RISK_LABEL: Record<string, string> = { low: '低', medium: '中', high: '中高', risk: '高' }

function deriveConclusion(r: DecisionRecord): string {
  const parts: string[] = []
  if (r.direction) parts.push(`方向：${r.direction}`)
  if (r.directionMatch) parts.push(`匹配 ${r.directionMatch}%`)
  if (r.riskLevel) parts.push(`风险${RISK_LABEL[r.riskLevel] ?? r.riskLevel}`)
  return parts.join('；') || '—'
}

/** 替换 INDEX 中 `## {title}` 到下一个 `## `（或文件尾）的段落；段落不存在 → 追加到文件尾 */
function replaceSection(md: string, title: string, body: string): string {
  const header = `## ${title}`
  const start = md.indexOf(header)
  if (start === -1) return `${md.replace(/\s*$/, '')}\n\n${header}\n\n${body}\n`
  const after = md.indexOf('\n## ', start + header.length)
  const end = after === -1 ? md.length : after
  return `${md.slice(0, start)}${header}\n\n${body}${md.slice(end)}`
}

/** 从 decisions/ 派生并重写 INDEX 的决策记录 + 城市评估段落（无效决策不投影——身份错误可见于信息池） */
export function writeIndexDecisionSections(ws: Workspace, parsed: ParsedDecision[]): void {
  // workspace API 的 relPath 语义：相对 root（绝对路径会被 path.join 拼接成 root\abs 导致 exists false）
  const indexPath = 'INDEX.md'
  if (!ws.exists(indexPath)) return
  const md = ws.read(indexPath)
  const persons = scanPersons(ws)
  const nameOf = (pid: string | undefined): string =>
    persons.find((p) => p.personId === pid)?.name ?? pid ?? '—'

  const valid = parsed.filter((p) => p.validation?.status !== 'invalid')
  const sorted = [...valid].sort((a, b) =>
    (a.record.createdAt < b.record.createdAt ? 1 : -1) || (a.sourceFile < b.sourceFile ? 1 : -1),
  )

  const decisionRows = sorted.map((p) => {
    const r = p.record
    return `| ${r.createdAt || '-'} | ${nameOf(r.personId)} | ${r.title} | ${r.skill} | ${deriveConclusion(r)} |`
  })
  const decisionBody = [
    '<!-- GENERATED BY ENGINE（decisions/ 派生）：请勿手动修改本段落 -->',
    '| 日期 | 用户 | 主题 | 来源 | 关键结论 |',
    '|------|------|------|------|---------|',
    ...decisionRows,
  ].join('\n')

  const cityRows = sorted
    .filter((p) => p.record.skill === 'city-advisor' && p.record.city)
    .map((p) => {
      const r = p.record
      const raw = ws.read(`decisions/${p.sourceFile}`)
      const score = parseSummaryTable(raw)?.city_score ?? ''
      return `| ${r.city} | decisions/${p.sourceFile} | ${r.createdAt || '-'} | ${score || '—'} |`
    })
  const cityBody = [
    '<!-- GENERATED BY ENGINE（decisions/ 派生）：请勿手动修改本段落 -->',
    '| 城市 | 文件 | 最后更新 | 得分 |',
    '|------|------|---------|:--:|',
    ...cityRows,
  ].join('\n')

  let next = replaceSection(md, '决策记录', decisionBody)
  next = replaceSection(next, '城市评估', cityBody)
  ws.write(indexPath, next)
}
