import { test } from 'node:test'
import assert from 'node:assert/strict'
import { mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { initWorkspace } from '../storage/workspace.ts'
import { scanDecisions } from '../storage/report-watcher.ts'
import { writeIndexDecisionSections } from '../storage/index-writer.ts'

function tempWorkspace(): { ws: ReturnType<typeof initWorkspace>; cleanup: () => void } {
  const dir = mkdtempSync(join(tmpdir(), 'cos-index-'))
  const ws = initWorkspace(dir)
  return { ws, cleanup: () => rmSync(dir, { recursive: true, force: true }) }
}

test('writeIndexDecisionSections：决策/城市段落引擎化 + generated 标记 + person 列继承', () => {
  const { ws, cleanup } = tempWorkspace()
  try {
    // 模拟存量 INDEX（Agent 手写段落 + 其他段落保留）
    ws.write(
      'INDEX.md',
      [
        '# 工作目录索引',
        '',
        '## 用户画像',
        '',
        '| 用户 | 文件 |',
        '|------|------|',
        '| 你好 | persons/person_003/ |',
        '',
        '## 决策记录',
        '',
        '| 日期 | 用户 | 主题 | 来源 | 关键结论 |',
        '|------|------|------|------|---------|',
        '| 2026-08-07 | 我 | 旧手写行 | career-path | 手写结论 |',
        '',
        '## 城市评估',
        '',
        '| 城市 | 文件 | 最后更新 | 得分 |',
        '|------|------|---------|:--:|',
        '| 旧城市 | 旧文件 | - | - |',
        '',
        '## 公司尽调',
        '',
        '| 公司 | 文件 |',
        '|------|------|',
        '| 某公司 | companies/某公司.md |',
      ].join('\n'),
    )
    // person manifest（scanPersons 解析 personId/name）
    ws.write(
      'persons/person_003/manifest.md',
      '---\nid: person_003\nname: 你好\nstatus: active\n---\n# Person 003\n\n## 分析摘要\n\n| 字段 | 值 |\n|------|-----|\n| id | person_003 |\n| name | 你好 |\n',
    )
    // 决策文件（frontmatter person_id）
    ws.write(
      'decisions/2026-08-07-城市评估.md',
      [
        '---',
        'id: decision_20260807_00001',
        'created_at: 2026-08-07',
        'person_id: person_003',
        '---',
        '# 城市评估 — City-X vs City-W',
        '',
        '## 分析摘要',
        '',
        '| 字段 | 值 |',
        '|------|-----|',
        '| skill | city-advisor |',
        '| direction | 机器人结构设计 |',
        '| direction_match | - |',
        '| city | City-X / City-W |',
        '| city_score | City-X 7.6 / City-W 6.95 |',
        '| risk_level | 中 |',
        '| key_risk | 测试风险 |',
        '| status | complete |',
        '| protocol_version | 2.0 |',
      ].join('\n'),
    )

    const parsed = scanDecisions(ws)
    writeIndexDecisionSections(ws, parsed)
    const next = ws.read('INDEX.md')
    console.log('DEBUG next 决策段:', JSON.stringify(next.slice(next.indexOf('决策记录') - 5, next.indexOf('决策记录') + 120)))

    // generated 标记
    assert.ok(next.includes('GENERATED BY ENGINE'), `决策段落应有 generated 标记。next=${JSON.stringify(next)}`)
    assert.ok(next.includes('请勿手动修改本段落'), '城市段落应有 generated 标记')
    // 旧手写行被替换
    assert.ok(!next.includes('旧手写行'), '旧手写决策行应被替换')
    assert.ok(!next.includes('旧城市'), '旧城市评估行应被替换')
    // person 列继承（person_id → display_name）
    assert.ok(next.includes('| 你好 |'), 'person 列应由 person_id 派生为展示名')
    assert.ok(next.includes('城市评估 — City-X vs City-W'), '新决策应出现在决策段落')
    assert.ok(next.includes('City-X 7.6 / City-W 6.95'), '城市得分应来自摘要表原文')
    // 其他段落保留
    assert.ok(next.includes('## 用户画像'), '用户画像段落保留')
    assert.ok(next.includes('## 公司尽调'), '公司尽调段落保留')
    assert.ok(next.includes('某公司'), '公司尽调内容保留')
  } finally {
    cleanup()
  }
})

test('writeIndexDecisionSections：城市段得分从明细段落 payload 派生（摘要表 city_score=-）', () => {
  const { ws, cleanup } = tempWorkspace()
  try {
    ws.write(
      'INDEX.md',
      [
        '# 工作目录索引',
        '',
        '## 用户画像',
        '',
        '| 用户 | 文件 |',
        '|------|------|',
        '| 你好 | persons/person_003/ |',
        '',
        '## 决策记录',
        '',
        '| 日期 | 用户 | 主题 | 来源 | 关键结论 |',
        '|------|------|------|------|---------|',
        '| - | - | - | - | - |',
      ].join('\n'),
    )
    ws.write('persons/person_003/manifest.md', '---\nid: person_003\nname: 你好\nstatus: active\n---\n# Person 003\n')
    ws.write(
      'decisions/2026-08-07-城市评估.md',
      [
        '---',
        'id: decision_20260807_00001',
        'created_at: 2026-08-07',
        'person_id: person_003',
        '---',
        '# 城市评估 — City-X vs City-W',
        '',
        '## 分析摘要',
        '',
        '| 字段 | 值 |',
        '|------|-----|',
        '| skill | city-advisor |',
        '| profile | 你好 |',
        '| direction | 机器人结构设计 |',
        '| direction_match | - |',
        '| city | - |',
        '| city_score | - |',
        '| risk_level | 中 |',
        '| key_risk | 测试风险 |',
        '| status | complete |',
        '| protocol_version | 2.8 |',
        '',
        '## 城市评估明细',
        '',
        '| 城市 | 得分 | 置信度 | 关键优势 | 关键风险 |',
        '|------|:--:|:--:|---------|---------|',
        '| City-X | 7.6/10 | 中 | 薪酬性价比/政策 | - |',
        '| City-W | 6.95/10 | - | 行业天花板 | - |',
      ].join('\n'),
    )

    const parsed = scanDecisions(ws)
    writeIndexDecisionSections(ws, parsed)
    const next = ws.read('INDEX.md')
    // 城市列从 payload 城市名重组；得分从 payload 派生（X/10 显示），非摘要表原文
    assert.ok(next.includes('| City-X / City-W |'), `城市列应重组自 payload。next=${JSON.stringify(next)}`)
    assert.ok(next.includes('City-X 7.6 / City-W 6.95'), '得分应从 payload 派生（76/10=7.6、69.5/10=6.95）')
    assert.ok(next.includes('城市评估 — City-X vs City-W'), '决策记录段落正常投影')
  } finally {
    cleanup()
  }
})
